##################
# near_lem_2018_assembly.sub
# Submission script for assembling near_lem_2018
#
##################

request_cpus = 23
request_memory = 200GB

executable = /opt/bifxapps/SPAdes-3.13.1/bin/spades.py
arguments = "-t 20 -m 200 --meta -k 21,33,55,77,99,127 -1 /home/GLBRCORG/trina.mcmahon/md2021/data/metagenomes/TrunkRiver/near_lem_GGACTCCT-AGAGTAGA_L001_R1_001.qcd.fastq.gz -2 /home/GLBRCORG/trina.mcmahon/md2021/data/metagenomes/TrunkRiver/near_lem_GGACTCCT-AGAGTAGA_L001_R2_001.qcd.fastq.gz -o /home/GLBRCORG/trina.mcmahon/md2021/analysis/TrunkRiver/assembly/near_lem/near_lem_2018_4"

output = /home/GLBRCORG/trina.mcmahon/outs/$(Cluster)_$(Process)_mapping.out
error = /home/GLBRCORG/trina.mcmahon/md2021/errs/$(Cluster)_$(Process)_mapping.err
log = /home/GLBRCORG/trina.mcmahon/md2021/logs/$(Cluster)_$(Process)_mapping.log

queue
