##################
# metabat_binning.sub
# Submission script for binning on GLBRC with MetaBat
# Elizabeth McDaniel
##################

request_cpus = 4
request_memory = 5GB

executable = /home/GLBRCORG/emcdaniel/EBPR/Abigail/executables/metabat-binning.sh

arguments = $(ASSEMB)

output = /home/GLBRCORG/emcdaniel/EBPR/Abigail/outs/$(Cluster)_$(Process)_binning.out
error = /home/GLBRCORG/emcdaniel/EBPR/Abigail/errs/$(Cluster)_$(Process)_binning.err
log = /home/GLBRCORG/emcdaniel/EBPR/Abigail/logs/$(Cluster)_$(Process)_binning.log

queue ASSEMB from /home/GLBRCORG/emcdaniel/EBPR/Abigail/metadata/Abigail-assemblies.txt
