##################
# reformat-fastq.sub
# Submission script for reformatting metagenomic reads
# Elizabeth McDaniel
##################

request_cpus = 4
request_memory = 10GB

executable = /home/GLBRCORG/emcdaniel/EBPR/Abigail/executables/reformat-fastq.sh
arguments = $(r1) $(r2) $(out)

output = /home/GLBRCORG/emcdaniel/EBPR/Abigail/outs/$(Cluster)_$(Process)_reformat.out
error = /home/GLBRCORG/emcdaniel/EBPR/Abigail/errs/$(Cluster)_$(Process)_reformat.err
log = /home/GLBRCORG/emcdaniel/EBPR/Abigail/logs/$(Cluster)_$(Process)_reformat.log

queue r1,r2,out from metadata/Abigail_metagenomes.txt
